Add details page
GregOnOff/capstone-project pull request #8
Opened 2022-11-29 12:47 UTC by GregOnOff

2022-11-29 13:46 UTC, shebtastic requested changes

2022-11-29 13:46 UTC, shebtastic commented on components/ItemCategoryIcon.js
> +          />
this could have been the `next/image` component, especially for locally served images.

the inline styles should maybe be replaced with styled components for consistency.

2022-11-29 13:46 UTC, shebtastic commented on components/ItemCategoryIcon.js
>    function getIconByCat(category) {
```suggestion
  function getIconByCategory(category) {
```

i wouldn't unnecessarily shorten names insignificantly, if you pay by reducing readability

2022-11-29 13:46 UTC, shebtastic commented on components/details/DetailsCard.jsx
> +  function findMe(item) {
```suggestion
  function findMe(item) {
```

is `Me` really the right term?

2022-11-29 13:46 UTC, shebtastic commented on components/details/DetailsCard.jsx
> +  const actualRoute = router.query.id;
renaming the id to actualRoute seems confusing
```suggestion
  const {id} = router.query;
```

2022-11-29 13:46 UTC, shebtastic commented on components/details/DetailsCard.jsx
> +    <>
unnecessary fragment

2022-11-29 13:46 UTC, shebtastic commented on components/Header.js
> +        <span>Do I really need that!?</span>
is the `span` part of the heading?

2022-11-29 13:46 UTC, shebtastic commented on components/details/DetailsCard.jsx
> +export default function DetailsCard({ items }) {
is `DetailsCard` your `default` for this whole folder? if so, could it be exported from the `index.js` and the folder renamed to adhere to the component name?

2022-11-29 13:46 UTC, shebtastic commented on components/details/DetailsCard.jsx
> +        <p>Added: {moment(details.date).calendar()}</p>
this could have been implemented with [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString)

2022-11-29 13:46 UTC, shebtastic commented on package.json
> +    "moment": "^2.29.4",
be aware that moment is considered legacy by its maintainers:

> We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.

https://momentjs.com/docs/

2022-11-29 13:46 UTC, shebtastic commented on pages/index.js
> +// import { BsPlusCircleDotted } from "react-icons/bs";
dead comment. if you need it, it will be in your git history.

```suggestion
```

2022-11-29 13:46 UTC, shebtastic commented on pages/index.js
> +              /> */}
dead comment. if you need it, it will be in your git history.

```suggestion
```

2022-11-29 13:46 UTC, shebtastic commented on pages/items/index.jsx
> +}
why does this page exist?

2022-11-29 20:55 UTC, GregOnOff commented on pages/items/index.jsx
> +}
I don't know either :(

2022-11-30 12:12 UTC, ahohnsen requested changes
Hey Greg,

Well done 💪🏼 I added some comments, please have a look 👀

2022-11-30 12:12 UTC, ahohnsen commented on pages/index.js
I see an unnecessary `div` in this page 🕵🏼 As you already have the fragments (`<></>`), you do not need the `div` element.
If I see correctly, you probably also do not need these styles for your `LinkStyled`:

```css
display: flex;
flex-direction: column;
```

Additionally, I think it is a bit unfortunate, that you import `itemData` and inside of that are your `wishlistItems`. The name `itemData` suggests that it includes data from only one single item. Either rename it or better, have a look at your data structure. 

Your localStorage entry looks like this:

```
data:"{
"wishlistItems": [
{"id":"i1","title":"Katzenbaby","price":"999.99","link":"https://amazon.com","category":"health","image":"images/placeholder.png","timeLeft":9}, ...
]}"
```

Why not name your localStorage entry "Wishlist" and place the array of items directly inside, e.g.:

```
wishlist:"[
{"id":"i1","title":"Katzenbaby","price":"999.99","link":"https://amazon.com","category":"health","image":"images/placeholder.png","timeLeft":9}, ...
]"
```

2022-11-30 12:12 UTC, ahohnsen commented on pages/items/[id].jsx
> +    </div>
See my comment above regarding `itemData`.
Additionally, there is a `div` here, you do not need.
```suggestion
      <DetailsCard items={itemData.wishlistItems} />
```

2022-12-01 10:13 UTC, JessicaLoers approved these changes
**Well done @GregOnOff  ✌️**
Just some small comments. 
I highly recommend to refactor your styling - but that's more a topic for the future Greg 🧑‍🚀

2022-12-01 10:13 UTC, JessicaLoers commented on components/DetailsCard/DetailsStyled.js
> +`;
Maybe it's a cleaner way to place your Link, instead of using `position`

```suggestion
const StyledLink = styled(Link)`
  position: absolute;
  border: 2px solid black;
  right: 50%;
  transform: translateX(50%);
  text-align: center;
  color: white;
  font-weight: 500;
  border: 2px solid #555;
  background-color: #e04e1a;
  font-size: 1.2rem;
  border-radius: 7px;
  text-decoration: none;
  padding: 10px;
  width: 120px;
`;
```

2022-12-01 10:13 UTC, JessicaLoers commented on components/DetailsCard/index.js
> +
please remove empty lines before you merge the PR 🧹

2022-12-01 22:46 UTC, merged